name: Example workflow for Maven using Snyk
#description: 'Snyk test demo for Maven 3.9.3/JAVA 17, linked to US - https://atc.bmwgroup.net/jira/browse/CAWE-790'

on: push
jobs:
  security:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Snyk CLI
        run: npm install -g snyk && npm update -g snyk && npm i -g snyk-recursive && npm update -g snyk-recursive && npm install snyk-to-html -g && echo "Snyk CLI already installed"

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif --command=monitor

      - name: Output original SARIF file
        run: cat snyk.sarif

      - name: Validate and fix SARIF file
        run: |
          jq '
          .runs[].tool.driver.rules |= map(
            if .properties["security-severity"] == null or .properties["security-severity"] == "undefined" then
              .properties["security-severity"] = "5.0"
            else
              .properties["security-severity"] |= tostring
            end
          )' snyk.sarif > fixed-snyk.sarif

      - name: Output fixed SARIF file
        run: cat fixed-snyk.sarif

      - name: Convert Sarif file to HTML
        # run: snk sarif-to-html -i fixed-snyk.sarif -o snyk-report.html
        run: snyk test --json | snyk-to-html -o results-opensource.html


      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: fixed-snyk.sarif





#      - name: Print the Snyk SARIF file
#        run: |
#          cat snyk.sarif

# --------------------------------------------------------------------

#name: Example workflow for Maven using Snyk
#on: push
#permissions:
#  actions: read
#  contents: read
#  security-events: write
#
#jobs:
#  security:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run Snyk to check for vulnerabilities
#        uses: snyk/actions/maven-3-jdk-17@master # Ajustado para a última versão estável conhecida
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          args: --all-projects --sarif-file-output=snyk.sarif --command=monitor
      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: snyk.sarif